<a href="https://colab.research.google.com/github/xinnazim/esaa/blob/main/0310_%EC%9C%A0%EC%A7%80%EB%AF%BC_1%EC%A3%BC%EC%B0%A8%EA%B3%BC%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[개념정리]

# 파이썬 머신러닝 완벽 가이드

## 1. 머신러닝의 개념

* 머신러닝:애플리케이션을 수정하지 않고도 데이터를 기반으로 패턴을 학습하고 결과를 예측하는 알고리즘 기법

## 2. 머신러닝의 분류

* 지도학습 
  * 분류
  * 회귀
  * 추천 시스템
  * 시각,음성 감지,인지
  * 텍스트 분석, NLP

* 비지도학습
  * 클러스터링
  * 차원 축소
  * 강화학습

## 3. 넘파이 : 선형대수 기반

* 데이터 타입: ndarray내의 숫자,문자열,불 모두 가능
  - 특성상 연산은 같은 데이터 타입만 가능

* 타입 변경 astype() 메서드 (ex.메모리 절약을 위해 float->int)

* arange() 함수 : range와 유사

* reshape(2,5) 메서드 : 특정 차원 및 크기로 변환

* 인덱싱 : 특정 데이터 선택

  * 특정 데이터 추출 - array1[row(axis0),col]/ axis0=row방향 축

  * 슬라이싱: array[1:3] -> 1,2

  * 팬시 인덱싱 : 리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray 반환 - array1[[0,1],2]

  * 불린 인덱싱 - array1[array1>5] , 조건문 그대로 적용

* 행렬의 정렬

  * sort()/ np.sort():원본 행렬 유지, 정렬된 형태 / ndarray.sort():반환값 none
  * argsort():  정렬 행렬의 원본 행렬 인덱스를 ndarray 형으로 반환환

* 선형대수 연산

  * 행렬내적(행렬곱)
    - np.dot(A,B)
  * 전치 행렬
    - transporse(A)



[필사]

In [22]:
import numpy as np

In [23]:
#array() 
array1 = np.array([1,2,3])
print('array1.type:',type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1,2,3],[2,3,4]])
print('array2.type:',type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1,2,3]])
print('array3.type:',type(array3))
print('array3 array 형태:', array3.shape)


array1.type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2.type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3.type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [24]:
#np.array() 차원 확인인
print('array1:{:0}차원,array2:{:1}차원,array3:{:2}차원'.format(array1.ndim,array2.ndim,array3.ndim))

array1:1차원,array2:2차원,array3: 2차원


In [25]:
#데이터 타입
list1=[1,2,3]
print(type(list1))
array1=np.array(list1)
print(type(array1))
print(array1,array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [26]:
# 데이터 유형이 섞여 있는 리스트-> ndarray
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype) 

#더 큰 데이터 타입으로 변환환

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [27]:
# astype()   float->int 메모리 부족 오류 예방
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [28]:
#ndarray 편리하게 생성

# 1. arange()  

sequency_array = np.arange(10)
print(sequency_array)
print(sequency_array.dtype,sequency_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [29]:
# 2.zeros() 

zero_array = np.zeros((3,2), dtype = 'int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

# 3. ones()

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [30]:
# reshape() 차원과 크기를 변경

array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n', array2)

array3 = array1.reshape(5,2)
print('array3:\n', array3)


array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [31]:
#변경 불가하면 오류
#array1.reshape(4,3)

In [32]:
#-1을 인자로 적용, 알아서 호환되는 새로운 shape로 변환환
array1 = np.arange(10)
print(array1)
array2=array1.reshape(-1,5)
print('array2 shape:',array2.shape)
array3 = array1.reshape(5,-1)
print('array3 shape:',array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [33]:
# 호환 불가
# array1=np.arange(10)
# array4=array1.reshape(-1,4)

In [34]:
# -1인자 reshape(-1,1):반드시 1개의 칼럼을 가진 ndarray로 변환됨됨 / tolist() 메서드로 리스트 자료형으로 변환
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())

#3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

#1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


In [35]:
# 인덱싱

# 단일값 추출


# 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1:', array1)

# index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value = array1[2]
print('value:', value)
print(type(value))
     

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [36]:

print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


In [37]:
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


In [44]:
# 다차원에서 단일값 추출

array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0,0])
print('(row=0, col=1) index 가리키는 값:', array2d[0,1])
print('(row=1, col=0) index 가리키는 값:', array2d[1,0])
print('(row=2, col=2) index 가리키는 값:', array2d[2,2])
     

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


In [39]:
# 슬라이싱 , 연속 데이터 추출출

array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [40]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:] 
print(array5)

#전체 선택택
array6 = array1[:] 
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [46]:
# 2차원 수준에서의 슬라이싱 로우,칼럼 인덱스 지칭
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print('array2d:\n', array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [47]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)


[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


In [48]:
# 팬시 인덱싱 : 리스트로 지정정
array1 = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1], 2] #0,1row의 2번째 col
print('array2d[[0,1], 2]=> ', array3.tolist()) #tolist> 리스트로 변환해줌줌

array4 = array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2]=> ', array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]]=> ', array5.tolist())

array2d[[0,1], 2]=>  [3, 6]
array2d[[0,1], 0:2]=>  [[1, 2], [4, 5]]
array2d[[0,1]]=>  [[1, 2, 3], [4, 5, 6]]


In [49]:
# 불린 인덱싱

array1d = np.arange(start=1, stop=10)

# [] 안에 array1d > 5 Boolean indexing을 적용

array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값:', array3)

array1d > 5 불린 인덱싱 결과 값: [6 7 8 9]


In [50]:
array1d>5

boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [51]:
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과 :', array4)

#True 값을 가진 인덱스를 저장하는 것, 값 자체인 1을 저장하진 않음음

일반 인덱스로 필터링 결과 : [6 7 8 9]


In [52]:
# 행렬의 정렬

org_array = np.array([ 3, 1, 9, 5])
print('원본 행렬:', org_array)

# np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)

#ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 정렬 행렬:', sort_array2) #반환 X
print('org_array.sort() 호출 후 원본 행렬:', org_array) #원행렬을 정렬해서 저장장

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 정렬 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


In [53]:
sort_array_desc=np.sort(org_array)[::-1]
print('내림차순으로 정렬:',sort_array_desc)

내림차순으로 정렬: [9 5 3 1]


In [54]:
array2d = np.array([[8,12],
                    [7, 1]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


In [55]:
# 정렬된 행렬의 기본 원본 행렬의 원소에 대한 인덱스 반환

# 오름차순
org_array = np.array([ 3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)


<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [56]:
# 내림차순
org_array = np.array([ 3, 1, 9, 5])
sort_indices_desc = np.argsort(org_array)[::-1]
print(type(sort_indices_desc))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [57]:
import numpy as np

# 데이터를 별도로 필요

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


In [58]:
# 선형대수 연산

#행렬 내적(행렬곱)

A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])
dot_product = np.dot(A,B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [59]:
# 전치행렬
#transpose() 이용

A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
