<a href="https://colab.research.google.com/github/xinnazim/esaa/blob/main/Numpy_0317.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)
np.show_config()
#버전체크

1.22.4
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
A=np.zeros(10) # 배열크기*원소
print("length : %d / itemsize : %d / memorysize : %d bytes" % (A.size  , A.itemsize ,A.size*A.itemsize))

length : 10 / itemsize : 8 / memorysize : 80 bytes


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
A=np.zeros(10)
A[4]=1
A

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
B=np.arange(10,50)
B[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
M=np.arange(0,9).reshape(3,3)
M

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
N=[1,2,0,0,4,0]
np.nonzero(N)

(array([0, 1, 4]),)

#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [ ]:
data = np.eye(3)  #np.eye():단위행렬 생성
print(data)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [ ]:
data = np.random.random((3,3,3)) # 넘파이>랜덤모듈>랜덤함수
data

array([[[0.07112421, 0.28598771, 0.67055584],
        [0.88131099, 0.59379463, 0.10135511],
        [0.07197891, 0.30042036, 0.62882871]],

       [[0.89847187, 0.47886327, 0.85842721],
        [0.83288173, 0.7341775 , 0.5434484 ],
        [0.76143465, 0.3197869 , 0.73360879]],

       [[0.54283689, 0.58685269, 0.50866304],
        [0.42580603, 0.65945747, 0.76926241],
        [0.2605228 , 0.98024297, 0.01121708]]])

#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [ ]:
data = np.random.random((10,10))
_min, _max = data.min(), data.max()
_min, _max

(0.006910801059790694, 0.9954422401759937)

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [ ]:
data = np.random.random(30)
print(data.mean())

0.5842088055102252


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
data = np.ones((5,5))
data[1:-1, 1:-1] = 0
data

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [ ]:
data = np.diag(1+np.arange(4), k = -1) #대각행렬함수
data

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
data = np.zeros((8,8)) # 간격 2씩 1 채우기
data[::2, 1::2] = 1
data[1::2,::2] = 1
data

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [ ]:
data = np.unravel_index(99, (6,7,8)) # 3차원
data

(1, 5, 3)

#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [ ]:
data=np.random.random((5,5))
Z = (data-np.mean(data)) / (np.std(data))
Z

array([[ 1.63134367, -1.41168591, -0.50279419, -0.68103901,  0.85921209],
       [-1.05877498, -0.2210075 ,  0.32538228,  0.35434367,  0.80482315],
       [-0.55817169,  1.21718051, -1.27501941, -0.90306693, -0.80513135],
       [-0.07521413, -1.22110233, -1.50878821,  0.53679693,  1.41425987],
       [ 0.71715574,  1.51524459, -0.93890973,  0.33881003,  1.44615285]])

#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [ ]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])


#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
data = np.dot(np.ones((5,3)), np.ones((3,2)))
print(data)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
D=np.arange(10)
D[(3<=D)&(D<=8)]*=-1
print(D)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))  
```

In [ ]:
print(sum(range(5),-1)) # -1,1,2,3,4 #sum과 np.sum의 차이
from numpy import * # 넘파이 함수 안의 기능 불러오기기
print(sum(range(5),-1)) # np.sum -1이 축이다.

#sum(sequence[,start]) python의 내장함수
#numpy.sum(a, axis=None)

9
10


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z=np.arange(10)

print(Z**Z)
print(2 << Z >> 2) # z의 2제곱곱
print(Z <- Z)
print(1j*Z)   # j 복소수
print(Z/1/1)
#print(Z<Z>Z)

[        1         1         4        27       256      3125     46656
    823543  16777216 387420489]
[  0   1   2   4   8  16  32  64 128 256]
[False False False False False False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)

<ipython-input-26-3585dcb7ab9b>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)


nan

In [ ]:
np.array(0) // np.array(0)

<ipython-input-27-4764261090d0>:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [ ]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [ ]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[3 4 0 7 8 9 9 0 4 4]
[6 5 0 8 0 5 3 7 2 4]
[0 3 4 7 8]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

# np.sqrt():음수의 제곱근과 같은 복잡한 결과 계산 불가가

<ipython-input-35-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

In [ ]:
import numpy as np

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [ ]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
Z

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3

np.add(A,B,out=B)
np.negative(A,out=A)
np.divide(A,2,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [ ]:
Z = np.random.uniform(0,10,10)
print(Z)

print(Z - Z%1)
print(np.floor(Z))
print(np.ceil(Z) - 1)
print(np.trunc(Z))

[6.98202111 8.39093327 9.09165696 6.22730442 4.64562249 7.96524104
 6.36536146 8.83104389 4.54763816 9.89850451]
[6. 8. 9. 6. 4. 7. 6. 8. 4. 9.]
[6. 8. 9. 6. 4. 7. 6. 8. 4. 9.]
[6. 8. 9. 6. 4. 7. 6. 8. 4. 9.]
[6. 8. 9. 6. 4. 7. 6. 8. 4. 9.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

#### 32. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
arr = np.random.random(10)
print(arr)

arr.sort()
arr

[0.18897333 0.87147766 0.10876161 0.90966763 0.5885116  0.35849956
 0.31572267 0.05359687 0.16985494 0.93998118]


array([0.05359687, 0.10876161, 0.16985494, 0.18897333, 0.31572267,
       0.35849956, 0.5885116 , 0.87147766, 0.90966763, 0.93998118])

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [51]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
np.array_equal(A,B)


False

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [ ]:
arr = np.random.random((10,2))
X,Y = arr[:,0], arr[:,1]

R = np.sqrt(X**2 + Y ** 2)
P = np.arctan2(Y,X) # 극좌표계

print(R)
print(P)
     

[0.73354224 0.44917252 0.57860419 1.13051347 0.84095786 0.73136857
 1.17473975 0.75591092 0.2510703  0.69803045]
[0.87359404 0.45666362 1.45903405 0.5806564  0.14448097 0.73978535
 0.87534586 0.40809047 0.8205763  0.92295882]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [52]:
z = np.random.random(10)
print(z)

z[z.argmax()] = 0
print(z)
     

[0.84401951 0.06356713 0.50959628 0.43548732 0.78497916 0.76621743
 0.58267709 0.42527222 0.67713078 0.37305426]
[0.         0.06356713 0.50959628 0.43548732 0.78497916 0.76621743
 0.58267709 0.42527222 0.67713078 0.37305426]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [ ]:
Z = np.arange(100)
v = np.random.uniform(0,100)
r = np.abs(Z-v)
Z[r.argmin()]

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [ ]:
Z = np.arange(9).reshape(3,3)

for index, value in np.ndenumerate(Z):
  print(index, value)

In [ ]:
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [ ]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

* 배열을 n번째 열로 정렬렬

In [ ]:
Z = np.random.randint(0,10,(3,3))
print(Z)

[[0 9 0]
 [1 5 7]
 [7 6 0]]


In [ ]:
# column 1
print(Z[Z[:,0].argsort()])

In [ ]:
# column 2
print(Z[Z[:,1].argsort()])

[[1 5 7]
 [7 6 0]
 [0 9 0]]


In [ ]:
# column 3
print(Z[Z[:,2].argsort()])

[[0 9 0]
 [7 6 0]
 [1 5 7]]
